apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: vault-tls
  dnsNames:
    - vault.check-consulting.net
  usages:
    - digital signature
    - key encipherment
