apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: default
spec:

  source:
    repoURL: "https://github.com/mchekini-check-consulting/scpi-argo-cd.git"
    path: "20-custom-resources/argo-cd/prd"
    targetRevision: HEAD
  destination:
    namespace: argo-cd
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true