apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogJ3NjcGktaW52ZXN0LWFwaScKICBzY3JhcGVfaW50ZXJ2YWw6IDE1cwogIG1ldHJpY3NfcGF0aDogJy9hY3R1YXRvci9wcm9tZXRoZXVzJwogIHN0YXRpY19jb25maWdzOgotICB0YXJnZXRzOiBbJ3NjcGktaW52ZXN0LWFwaS5zY3BpLWludmVzdC1pbnQ6ODA4MCddCg==
