apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - certificate.yml
  - ingress.yml


helmCharts:
  - name: matomo
    repo: https://charts.bitnami.com/bitnami
    releaseName: matomo
    version: 8.0.13
    valuesFile: values.yml