apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Content-Security-Policy "frame-src 'self' https://keycloak.check-consulting.net" always;
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.check-consulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
  tls:
    - hosts:
        - keycloak.check-consulting.net
      secretName: keycloak-tls