apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
        @type tail
        path /var/log/containers/scpi-invest-api*.log
        pos_file /var/log/fluentd-containers.log.pos
        tag kubernetes.*
        <parse>
            @type regexp
            expression /^(?<time>[^ ]+ [^ ]+) (?<level>INFO|ERROR|WARN|DEBUG|TRACE) +(?<pid>[^ ]+) --- \[(?<thread>[^\]]+)\] (?<logger>[^ ]+) +: (?<message>.*)$/
            time_format %Y-%m-%d %H:%M:%S.%L
        </parse>
        format none  # Ajout de ce format pour spécifier qu'il n'y a pas de format particulier en amont
    </source>

    <filter kubernetes.**>
       @type grep
       <regexp>
            key $.kubernetes.labels.app
            pattern ^scpi-invest-api$
       </regexp>
       format none
    </filter>
    
    <filter kubernetes.**>
        @type parser
        key_name log
        <parse>
            @type regexp
            expression /^(?<time>[^ ]+ [^ ]+) (?<level>INFO|ERROR|WARN|DEBUG|TRACE) +(?<pid>[^ ]+) --- \[(?<thread>[^\]]+)\] (?<logger>[^ ]+) +: (?<message>.*)$/
            time_format %Y-%m-%d %H:%M:%S.%L
        </parse>
        format none
    </filter>

    <match **>
      @type elasticsearch
      host "elasticsearch"
      port "9200"
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      flush_interval 5s
      content_type "application/json" 
    </match>
    

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-config
              mountPath: /fluentd/etc/
              readOnly: false
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-config
          configMap:
            name: fluentd-config


