apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5045
      }
    }
    
    

    filter {
      grok {
        match => {
           "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{GREEDYDATA:applicationName}\] \[%{WORD:environment}\] \[%{DATA:thread}\] %{LOGLEVEL:loglevel}  %{GREEDYDATA:logger} - %{GREEDYDATA:logmessage}"
        }
      }
      date {
         match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
         target => "@timestamp"
      }
    
      mutate {
        remove_field => ["timestamp"]
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        manage_template => "false"
        index => "apps-logs"
      }
      stdout { codec => rubydebug }
    }
    
    
    
