harborAdminPassword: "mchekini-test"

# Expose Service Configuration
expose:
  type: clusterIP            # Exposition via Ingress
  tls:
    enabled: false          # Activez TLS pour sécuriser l'accès
    auto:
      tls:
          commonName: ""
    certSource: auto       # Permet de générer automatiquement le certificat (auto-signé)
  ingress:
    hosts:
      core: harbor.check-consulting.net  # Remplacez par votre domaine pour Harbor
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  externalURL: https://harbor.check-consulting.net  # Lien externe pour accéder à Harbor

# Base de Données
database:
  type: internal                # Utilisation de la base de données interne (PostgreSQL)
  internal:
    password: "db_password"     # Mot de passe pour PostgreSQL interne, à personnaliser

# Redis
redis:
  type: internal                # Utilisation de Redis interne
  internal:
    password: "redis_password"  # Mot de passe pour Redis, à personnaliser