# values.yml

harborAdminPassword: "admin_password"
adminPassword: "admin_password"

externalURL: "https://harbor.check-consulting.net"

# Ingress pour exposer Harbor
ingress:
  enabled: false
  hosts:
    core: harbor.check-consulting.net  # Assurez-vous que ce domaine est correctement configuré dans votre DNS
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Utilisez la classe d'Ingress correspondant à votre cluster
    nginx.ingress.kubernetes.io/proxy-body-size: "0"  # Permet d'accepter des images de grande taille

  tls:
    - hosts:
        - harbor.check-consulting.net
      secretName: harbor-tls

postgresql:
  enabled: true
  postgresqlPassword: "postgres_password"

redis:
  enabled: true
  password: "redis_password"

# Stockage des données
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 10Gi  # Taille du stockage pour le registre
    jobservice:
      size: 1Gi   # Taille du stockage pour le service de jobs
    database:
      size: 5Gi   # Taille du stockage pour la base de données
    redis:
      size: 1Gi   # Taille du stockage pour Redis

# Désactiver les composants optionnels pour simplifier la configuration
chartmuseum:
  enabled: false

clair:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: false
