apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt
    solvers:
      - dns01:
          route53:
            region: eu-east-1
            hostedZoneID: Z02992983P6JBHBJ5UT37
            accessKeyIDSecretRef:
              name: cert-manager
              key: accessKey
            secretAccessKeySecretRef:
              name: cert-manager
              key: secretAccessKey