apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
spec:
  generators:
    - git:
        repoURL: "https://github.com/mchekini-check-consulting/scpi-argo-cd"
        revision: main
        directories:
          - path: '10-operators/*/prd'
  template:
    metadata:
      name: '{{ path[1] }}-operator'
    spec:
      destination:
       name: in-cluster
       namespace: '{{ path[1] }}'
      source:
        repoURL: "https://github.com/mchekini-check-consulting/scpi-argo-cd"
        targetRevision: main
        path: '{{ path }}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
