apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-ui-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: kafka-ui-tls
  dnsNames:
    - kafka-ui.check-consulting.net
  usages:
    - digital signature
    - key encipherment
