apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins


resources:
  - certificate.yml
  - ingress.yml


helmCharts:
  - name: jenkins
    releaseName: jenkins
    repo: https://charts.bitnami.com/bitnami
    version: 13.4.23
    valuesFile: values.yml