apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  source:
    repoURL: "https://github.com/mchekini-check-consulting/scpi-argo-cd.git"
    path: "30-applications/prd"
    targetRevision: main
  destination:
    name: "in-cluster"
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
