apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-prd
spec:
  destination:
    name: in-cluster
    namespace: config
  project: default
  source:
    repoURL: "https://github.com/mchekini-check-consulting/scpi-argo-cd.git"
    path: "05-config"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true